### ISSUE TITLE
do /help

### ISSUE THREAD

**Issue by DoNotFeedThePidgeons** [VaccinoPower/population-paced-borders#3]
i dont understand ur commands man do /help and commands list and explain

**Comment by DoNotFeedThePidgeons** [comment]
Команды сделай хоть какие-то, релоад там

**Comment by VaccinoPower** [comment]
Commands added:
/ppb [bal/balance]: shows expansion balance
/ppb send <amount>: send money to balance
/ppb reload: reload config
